package co.edu.uco.libreriauco.libreriauco.transversal.Catalogo;

public class CatalogoMensajes {
    private CatalogoMensajes(){}
   public static class UtilSql{
        private UtilSql(){}
       // en este primero si es de sql excepcion
       public static final String USUARIO_ERROR_PROBLEMA_VALIDANDO_SI_CONEXION_SQL_ESTA_ABIERTA = "Se ha presentado un problema tratando de validar si la conexion contra la fuente de informacion en la cual se iba a tratar de llevar a cabo la operacion deseada estaba o no abierta. Por favor intente de nuevo y si el problema persiste contacte al administrador de la aplicacion y reporte la novedad ";
        // aqui es el generico , es el por defecto , no controlado
       public static final String USUARIO_ERROR_PROBLEMA_NO_CONTROLADO_VALIDANDO_SI_CONEXION_SQL_ESTA_ABIERTA = "Se ha presentado un problema NO CONTROLADO tratando de validar si la conexion contra la fuente de informacion en la cual se iba a tratar de llevar a cabo la operacion deseada estaba o no abierta. Por favor intente de nuevo y si el problema persiste contacte al administrador de la aplicacion y reporte la novedad ";
       public static final String USUARIO_ERROR_PROBLEMA_VALIDANDO_SI_TRANSACCION_SQL_ESTA_INICIADA = "Se ha presentado un problema  tratando de validar si la conexion contra la fuente de informacion estaba en un estado consistente al tratar de llevar a cabo la operacion deseada. Por favor intente de nuevo y si el problema persiste contacte al administrador de la aplicacion y reporte la novedad ";
       public static final String USUARIO_ERROR_PROBLEMA_NO_CONTROLADO_VALIDANDO_SI_TRANSACCION_SQL_ESTA_INICIADA = "Se ha presentado un problema NO CONTROLADO tratando de validar si la conexion contra la fuente de informacion estaba en un estado consistente al tratar de llevar a cabo la operacion deseada. Por favor intente de nuevo y si el problema persiste contacte al administrador de la aplicacion y reporte la novedad ";
       public static  final String USUARIO_ERROR_NO_ES_POSIBLE_INICIAR_TRANSACCION_SQL = "No es posible continuar con la operacion deseada debido a que la conexion contra la fuente de informacion se encuentra en un estado inconsistente por que esta cerrada , esta vacia , o por que la transaccion ya fue iniciada. Por favor intente de nuevo y si el problema persiste contacte al administrador de la aplicacion y reporte la novedad ";
       public static final String USUARIO_ERROR_PROBLEMA_CERRANDO_CONEXION_SQL = "Se ha presentado un problema tratando de validar si la conexion contra la fuente de informacion en la cual se iba a tratar de llevar a cabo la operacion deseada se podia cerrar . Por favor intente de nuevo y si el problema persiste contacte al administrador de la aplicacion y reporte la novedad ";
       public static final String USUARIO_ERROR_PROBLEMA_NO_CONTROLADO_CERRANDO_CONEXION_SQL = "Se ha presentado un problema NO CONTROLADO tratando de validar si la conexion contra la fuente de informacion en la cual se iba a tratar de llevar a cabo la operacion deseada se podia cerrar. Por favor intente de nuevo y si el problema persiste contacte al administrador de la aplicacion y reporte la novedad ";
       public static final String USUARIO_ERROR_PROBLEMA_INICIANDO_TRANSACCION_SQL = "Se ha presentado un problema  tratando de iniciar  la transaccion contra la fuente de informacion . Por favor intente de nuevo y si el problema persiste contacte al administrador de la aplicacion y reporte la novedad ";
       public static final String USUARIO_ERROR_PROBLEMA_NO_CONTROLADO_INICIANDO_TRANSACCION_SQL = "Se ha presentado un problema NO CONTROLADO  tratando de iniciar  la transaccion contra la fuente de informacion . Por favor intente de nuevo y si el problema persiste contacte al administrador de la aplicacion y reporte la novedad ";
       public static final String USUARIO_ERROR_PROBLEMA_COMFIRMANDO_TRANSACCION_SQL = "Se ha presentado un problema  tratando de confirmar  la transaccion contra la fuente de informacion . Por favor intente de nuevo y si el problema persiste contacte al administrador de la aplicacion y reporte la novedad ";
       public static final String USUARIO_ERROR_PROBLEMA_NO_CONTROLADO_CONFIRMANDO_TRANSACCION_SQL = "Se ha presentado un problema NO CONTROLADO  tratando de confirmar  la transaccion contra la fuente de informacion . Por favor intente de nuevo y si el problema persiste contacte al administrador de la aplicacion y reporte la novedad ";
       public static final String USUARIO_ERROR_PROBLEMA_CANCELANDO_TRANSACCION_SQL = "Se ha presentado un problema  tratando de cancelar  la transaccion contra la fuente de informacion . Por favor intente de nuevo y si el problema persiste contacte al administrador de la aplicacion y reporte la novedad ";
       public static final String USUARIO_ERROR_PROBLEMA_NO_CONTROLADO_CANCELANDO_TRANSACCION_SQL = "Se ha presentado un problema NO CONTROLADO  tratando de cancelar  la transaccion contra la fuente de informacion . Por favor intente de nuevo y si el problema persiste contacte al administrador de la aplicacion y reporte la novedad ";
       public static final String USUARIO_ERROR_CONEXION_SQL_NO_ESTA_ABIERTA= "No es posible continuar con la operacion deseada debido a que la conexion contra la fuente de informacion esta vacia o se encuentra cerrada. Por favor intente de nuevo y si el problema persiste contacte al administrador de la aplicacion y reporte la novedad";
       public static final String USUARIO_ERROR_NO_ES_POSIBLE_CONFIRMAR_TRANSACCION_SQL ="No es posible confirmar los cambios de la operacion deseada debido a que la conexion contra la fuente de informacion esta vacia , esta cerrada , o por que la transaccion no fue iniciada. Por favor intente de nuevo y si el problema persiste contacte al administrador de la aplicacion y reporte la novedad ";
       public static final String USUARIO_ERROR_NO_ES_POSIBLE_CANCELAR_TRANSACCION_SQL ="No es posible deshacer los cambios de la operacion deseada debido a que la conexion contra la fuente de informacion esta vacia , esta cerrada , o por que la transaccion no fue iniciada. Por favor intente de nuevo y si el problema persiste contacte al administrador de la aplicacion y reporte la novedad ";
       public static final String USUARIO_ERROR_NO_ES_POSIBLE_CERRAR_CONEXION_SQL = "No es posible cerrar la conexion contra la fuente de informacion debido a que esta vacia o ya se encuentra cerrada. Por favor intente de nuevo y si el problema persiste contacte al administrador de la aplicacion y reporte la novedad ";

   }
   public static  class PaisSqlServerDao{
        private PaisSqlServerDao (){
        }
       public static final String USUARIO_ERROR_PROBLEMA_CREANDO_PAIS = "Se ha presentado un problema tratando de registrar la informacion del nuevo pais. Por favor intente de nuevo y si el problema persiste contacte al administrador de la aplicacion y reporte la novedad ";
       public static final String USUARIO_ERROR_PROBLEMA_NO_CONTROLADO_CREANDO_PAIS = "Se ha presentado un problema NO CONTROLADO tratando de registrar la informacion del nuevo pais. Por favor intente de nuevo y si el problema persiste contacte al administrador de la aplicacion y reporte la novedad ";
       public static final String USUARIO_ERROR_PROBLEMA_ACTUALIZANDO_PAIS = "Se ha presentado un problema tratando de actualizar la informacion del pais deseado. Por favor intente de nuevo y si el problema persiste contacte al administrador de la aplicacion y reporte la novedad ";
       public static final String USUARIO_ERROR_PROBLEMA_NO_CONTROLADO_ACTUALIZANDO_PAIS = "Se ha presentado un problema NO CONTROLADO tratando de actualizar la informacion del pais deseado. Por favor intente de nuevo y si el problema persiste contacte al administrador de la aplicacion y reporte la novedad ";
       public static final String USUARIO_ERROR_PROBLEMA_CONSULTANDO_PAIS_POR_ID= "Se ha presentado un problema tratando de consultar la informacion del pais deseado. Por favor intente de nuevo y si el problema persiste contacte al administrador de la aplicacion y reporte la novedad ";
       public static final String USUARIO_ERROR_PROBLEMA_NO_CONTROLADO_CONSULTANDO_PAIS_POR_ID = "Se ha presentado un problema NO CONTROLADO tratando de consultar la informacion del pais deseado. Por favor intente de nuevo y si el problema persiste contacte al administrador de la aplicacion y reporte la novedad ";
       public static final String USUARIO_ERROR_PROBLEMA_CONSULTANDO_PAIS_POR_FILTRO = "Se ha presentado un problema tratando de consultar la informacion  deseada. Por favor intente de nuevo y si el problema persiste contacte al administrador de la aplicacion y reporte la novedad ";
       public static final String USUARIO_ERROR_PROBLEMA_NO_CONTROLADO_CONSULTANDO_PAIS_POR_FILTRO = "Se ha presentado un problema NO CONTROLADO tratando de consultar la informacion deseada. Por favor intente de nuevo y si el problema persiste contacte al administrador de la aplicacion y reporte la novedad ";
       public static final String USUARIO_ERROR_PROBLEMA_CONSULTANDO_TODOS_LOS_PAISES = "Se ha presentado un problema tratando de consultar la informacion de todos los paises. Por favor intente de nuevo y si el problema persiste contacte al administrador de la aplicacion y reporte la novedad ";
       public static final String USUARIO_ERROR_PROBLEMA_NO_CONTROLADO_CONSULTANDO_TODOS_LOS_PAISES = "Se ha presentado un problema NO CONTROLADO tratando de consultar la informacion de todos los paises. Por favor intente de nuevo y si el problema persiste contacte al administrador de la aplicacion y reporte la novedad ";
       public static final String USUARIO_ERROR_PROBLEMA_ELIMINANDO_PAIS = "Se ha presentado un problema tratando de eliminar la informacion del pais deseado. Por favor intente de nuevo y si el problema persiste contacte al administrador de la aplicacion y reporte la novedad ";
       public static final String USUARIO_ERROR_PROBLEMA_NO_CONTROLADO_ELIMINANDO_PAIS = "Se ha presentado un problema NO CONTROLADO tratando de eliminar la informacion del pais deseado. Por favor intente de nuevo y si el problema persiste contacte al administrador de la aplicacion y reporte la novedad ";
   }

}
